### ISSUE TITLE
No changelog/release entry

### ISSUE THREAD

**Issue by stdedos** [joue-quroi/canvas-fingerprint-blocker#6]
I am wondering what are the updates, given this repo appears dead for 2 years

![image](https://user-images.githubusercontent.com/133706/83063923-96c93380-a069-11ea-938d-bf5a38e9330a.png)

**Comment by joue-quroi** [comment]
Nothing important to mention; See https://github.com/joue-quroi/canvas-fingerprint-blocker/commit/4cc8d99aba3d26199ec2c6f0c7da5c7057f69e9e

The minimum option width limitation is removed to fix the Edge issue.
